version: '3'
services:
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  cartcom-api:
    container_name: cartcom-api
    build:
      context: .
      dockerfile: Dockerfile
    image:
      gattal/commerce-api
    volumes:
      - ./api:/app/api
      - ./rules:/app/rules
      - ./config:/app/config
    depends_on:
      - db
    ports: 
      - 9080:9080
    networks:
      - default
    command: sh -c "sleep 10s && ./cartcom"
  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    environment: 
      - API_URL=http://localhost:9080/1.0/api/openapi.yaml
    ports: 
      - 9090:8080
    depends_on:
      - cartcom-api
    networks:
      - default
        
networks: 
  default: